services:
  symfony:
    image: kcordes/katiecordescodes-adventofcode-featureflags-symfony
    env_file:
      - .env.docker
    healthcheck:
      test: curl --fail http://localhost/ping || exit 1
      interval: 30s
      start_period: 10s
      timeout: 10s
    networks:
      katiecordescodes-adventofcode:
        aliases:
          - featureflags

  redis:
    env_file:
      - .env.docker

  splitio:
    env_file:
      - .env.docker


networks:
  katiecordescodes-adventofcode:
    external: true