name: katiecordescodes-adventofcode-featureflags

services:
  symfony:
    image: nginx/unit:1.29.0-php8.1

  redis:
    image: redis:7.0.8-alpine

  splitio:
    image: splitsoftware/split-synchronizer
    environment:
      SPLIT_SYNC_REDIS_HOST: redis
      SPLIT_SYNC_REDIS_PORT: 6379
